module.exports = {

    READY_EVENT: 'READY_EVENT',

    CONNECT_EVENT: 'CONNECT_EVENT',
    DISCONNECT_EVENT: 'DISCONNECT_EVENT',
    RESET_EVENT: 'RESET_EVENT',

    DNS_REQUEST_EVENT: 'DNS_REQUEST_EVENT',
    DNS_RESPONSE_EVENT: 'DNS_RESPONSE_EVENT',

    HTTP_REQUEST_EVENT: 'HTTP_REQUEST_EVENT',
    HTTP_RESPONSE_EVENT: 'HTTP_RESPONSE_EVENT',

    HTTPS_REQUEST_EVENT: 'HTTPS_REQUEST_EVENT',
    HTTPS_RESPONSE_EVENT: 'HTTPS_RESPONSE_EVENT',

    MAIL_EVENT: 'MAIL_EVENT'

    // DISCONNECT_EVENT: 'DISCONNECT_EVENT',
    // DISCONNECT_EVENT: 'DISCONNECT_EVENT',
    // DISCONNECT_EVENT: 'DISCONNECT_EVENT',
};