module.exports = {
    CONNECT_EVENT: 'CONNECT_EVENT',
    DISCONNECT_EVENT: 'DISCONNECT_EVENT',

    DNS_REQUEST_EVENT: 'DNS_REQUEST_EVENT',
    DNS_RESPONSE_EVENT: 'DNS_RESPONSE_EVENT',

    HTTP_REQUEST_EVENT: 'HTTP_REQUEST_EVENT',
    HTTP_RESPONSE_EVENT: 'HTTP_RESPONSE_EVENT',

    HTTPS_REQUEST_EVENT: 'HTTPS_REQUEST_EVENT',
    HTTPS_RESPONSE_EVENT: 'HTTPS_RESPONSE_EVENT',

    // DISCONNECT_EVENT: 'DISCONNECT_EVENT',
    // DISCONNECT_EVENT: 'DISCONNECT_EVENT',
    // DISCONNECT_EVENT: 'DISCONNECT_EVENT',
};